-- =========================
-- Users table
-- =========================
CREATE TABLE IF NOT EXISTS app_users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

-- =========================
-- Schema
-- =========================
CREATE SCHEMA IF NOT EXISTS primer_tool;

-- ==========
-- Enum type 
-- ===========
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type
        WHERE typname = 'yes_no'
    ) THEN
        CREATE TYPE yes_no AS ENUM ('Yes', 'No');
    END IF;
END$$;

-- =========================
-- Primers table (unique)
-- =========================
CREATE TABLE IF NOT EXISTS primer_tool.primers (
    unique_primer_id SERIAL PRIMARY KEY,

    chr VARCHAR(3) NOT NULL CHECK (
        chr IN ('X', 'Y')
        OR (chr ~ '^[0-9]+$' AND chr::int BETWEEN 1 AND 22)
    ),

    start_pos INTEGER NOT NULL CHECK (start_pos > 0 AND start_pos <= 300000000),
    end_pos INTEGER NOT NULL CHECK (end_pos > 0 AND end_pos <= 300000000),
    primer_name VARCHAR(100),
    left_primer_seq VARCHAR(50),
    right_primer_seq VARCHAR(50),
    left_primer_start INTEGER CHECK (left_primer_start >= 0),
    left_primer_end INTEGER CHECK (left_primer_end >= 0),
    right_primer_start INTEGER CHECK (right_primer_start >= 0),
    right_primer_end INTEGER CHECK (right_primer_end >= 0),
    product_size INTEGER CHECK (product_size > 0 AND product_size < 10000),
    gene VARCHAR(20),
    grch INTEGER NOT NULL CHECK (grch IN (37, 38)),

    CONSTRAINT unique_primer_identity UNIQUE (
        chr,
        primer_name,
        grch,
        left_primer_seq,
        right_primer_seq,
        left_primer_start,
        left_primer_end,
        right_primer_start,
        right_primer_end,
        product_size,
        gene
    )
);

-- =========================
-- Batch table (Non-unique)
-- =========================
CREATE TABLE IF NOT EXISTS primer_tool.primer_batches (
    primer_id INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 20000)
        PRIMARY KEY,

    unique_primer_id INTEGER NOT NULL,
    tagged_left VARCHAR(100),
    tagged_right VARCHAR(100),
    tag VARCHAR(10),
    notes VARCHAR(100),
    passed_validation yes_no,
    archive yes_no,
    mix VARCHAR(100),
    dilution_date VARCHAR(100),
    tray VARCHAR(100),
    freezer VARCHAR(100),
    grid_fw VARCHAR(100),
    grid_rv VARCHAR(100),
    manufacturer VARCHAR(100),
    insert_time TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_primer
        FOREIGN KEY (unique_primer_id)
        REFERENCES primer_tool.primers(unique_primer_id)
        ON DELETE CASCADE
);
-- =========================
-- Index
-- =========================
CREATE INDEX IF NOT EXISTS idx_primer_batches_primer_id
ON primer_tool.primer_batches(unique_primer_id);